/** Versículo del día: rotación anual determinista por fecha (sin backend).
 *
 * 838 referencias curadas (los 66 libros): con longitud >= 366 ningún
 * versículo se repite dentro del mismo año; el desplazamiento por año reparte
 * el ciclo en años sucesivos.
 */

export interface VerseRef {
    book: string;
    bookName: string;
    chapter: number;
    verse: number;
    label: string;
}

export const VERSE_ROTATION: VerseRef[] = [
    { book: 'genesis', bookName: 'Génesis', chapter: 1, verse: 1, label: 'Génesis 1:1' },
    { book: 'genesis', bookName: 'Génesis', chapter: 1, verse: 3, label: 'Génesis 1:3' },
    { book: 'genesis', bookName: 'Génesis', chapter: 1, verse: 27, label: 'Génesis 1:27' },
    { book: 'genesis', bookName: 'Génesis', chapter: 2, verse: 7, label: 'Génesis 2:7' },
    { book: 'genesis', bookName: 'Génesis', chapter: 3, verse: 15, label: 'Génesis 3:15' },
    { book: 'genesis', bookName: 'Génesis', chapter: 12, verse: 2, label: 'Génesis 12:2' },
    { book: 'genesis', bookName: 'Génesis', chapter: 15, verse: 6, label: 'Génesis 15:6' },
    { book: 'genesis', bookName: 'Génesis', chapter: 17, verse: 1, label: 'Génesis 17:1' },
    { book: 'genesis', bookName: 'Génesis', chapter: 18, verse: 14, label: 'Génesis 18:14' },
    { book: 'genesis', bookName: 'Génesis', chapter: 22, verse: 8, label: 'Génesis 22:8' },
    { book: 'genesis', bookName: 'Génesis', chapter: 28, verse: 15, label: 'Génesis 28:15' },
    { book: 'genesis', bookName: 'Génesis', chapter: 32, verse: 10, label: 'Génesis 32:10' },
    { book: 'genesis', bookName: 'Génesis', chapter: 37, verse: 1, label: 'Génesis 37:1' },
    { book: 'genesis', bookName: 'Génesis', chapter: 39, verse: 2, label: 'Génesis 39:2' },
    { book: 'genesis', bookName: 'Génesis', chapter: 41, verse: 16, label: 'Génesis 41:16' },
    { book: 'genesis', bookName: 'Génesis', chapter: 45, verse: 5, label: 'Génesis 45:5' },
    { book: 'genesis', bookName: 'Génesis', chapter: 50, verse: 20, label: 'Génesis 50:20' },
    { book: 'exodus', bookName: 'Éxodo', chapter: 3, verse: 14, label: 'Éxodo 3:14' },
    { book: 'exodus', bookName: 'Éxodo', chapter: 4, verse: 12, label: 'Éxodo 4:12' },
    { book: 'exodus', bookName: 'Éxodo', chapter: 12, verse: 13, label: 'Éxodo 12:13' },
    { book: 'exodus', bookName: 'Éxodo', chapter: 14, verse: 14, label: 'Éxodo 14:14' },
    { book: 'exodus', bookName: 'Éxodo', chapter: 15, verse: 2, label: 'Éxodo 15:2' },
    { book: 'exodus', bookName: 'Éxodo', chapter: 16, verse: 4, label: 'Éxodo 16:4' },
    { book: 'exodus', bookName: 'Éxodo', chapter: 19, verse: 5, label: 'Éxodo 19:5' },
    { book: 'exodus', bookName: 'Éxodo', chapter: 20, verse: 3, label: 'Éxodo 20:3' },
    { book: 'exodus', bookName: 'Éxodo', chapter: 20, verse: 12, label: 'Éxodo 20:12' },
    { book: 'exodus', bookName: 'Éxodo', chapter: 23, verse: 25, label: 'Éxodo 23:25' },
    { book: 'exodus', bookName: 'Éxodo', chapter: 31, verse: 18, label: 'Éxodo 31:18' },
    { book: 'exodus', bookName: 'Éxodo', chapter: 33, verse: 14, label: 'Éxodo 33:14' },
    { book: 'exodus', bookName: 'Éxodo', chapter: 34, verse: 6, label: 'Éxodo 34:6' },
    { book: 'exodus', bookName: 'Éxodo', chapter: 40, verse: 34, label: 'Éxodo 40:34' },
    { book: 'levitico', bookName: 'Levítico', chapter: 11, verse: 44, label: 'Levítico 11:44' },
    { book: 'levitico', bookName: 'Levítico', chapter: 16, verse: 30, label: 'Levítico 16:30' },
    { book: 'levitico', bookName: 'Levítico', chapter: 19, verse: 2, label: 'Levítico 19:2' },
    { book: 'levitico', bookName: 'Levítico', chapter: 19, verse: 18, label: 'Levítico 19:18' },
    { book: 'levitico', bookName: 'Levítico', chapter: 20, verse: 26, label: 'Levítico 20:26' },
    { book: 'levitico', bookName: 'Levítico', chapter: 26, verse: 3, label: 'Levítico 26:3' },
    { book: 'levitico', bookName: 'Levítico', chapter: 26, verse: 12, label: 'Levítico 26:12' },
    { book: 'numeros', bookName: 'Números', chapter: 6, verse: 24, label: 'Números 6:24' },
    { book: 'numeros', bookName: 'Números', chapter: 6, verse: 25, label: 'Números 6:25' },
    { book: 'numeros', bookName: 'Números', chapter: 6, verse: 26, label: 'Números 6:26' },
    { book: 'numeros', bookName: 'Números', chapter: 11, verse: 23, label: 'Números 11:23' },
    { book: 'numeros', bookName: 'Números', chapter: 14, verse: 18, label: 'Números 14:18' },
    { book: 'numeros', bookName: 'Números', chapter: 21, verse: 8, label: 'Números 21:8' },
    { book: 'numeros', bookName: 'Números', chapter: 23, verse: 19, label: 'Números 23:19' },
    { book: 'numeros', bookName: 'Números', chapter: 24, verse: 17, label: 'Números 24:17' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 4, verse: 29, label: 'Deuteronomio 4:29' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 6, verse: 4, label: 'Deuteronomio 6:4' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 6, verse: 5, label: 'Deuteronomio 6:5' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 6, verse: 6, label: 'Deuteronomio 6:6' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 7, verse: 9, label: 'Deuteronomio 7:9' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 8, verse: 3, label: 'Deuteronomio 8:3' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 10, verse: 12, label: 'Deuteronomio 10:12' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 11, verse: 18, label: 'Deuteronomio 11:18' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 28, verse: 2, label: 'Deuteronomio 28:2' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 29, verse: 29, label: 'Deuteronomio 29:29' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 30, verse: 19, label: 'Deuteronomio 30:19' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 31, verse: 6, label: 'Deuteronomio 31:6' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 32, verse: 4, label: 'Deuteronomio 32:4' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 33, verse: 27, label: 'Deuteronomio 33:27' },
    { book: 'deuteronomio', bookName: 'Deuteronomio', chapter: 34, verse: 10, label: 'Deuteronomio 34:10' },
    { book: 'josue', bookName: 'Josué', chapter: 1, verse: 5, label: 'Josué 1:5' },
    { book: 'josue', bookName: 'Josué', chapter: 1, verse: 7, label: 'Josué 1:7' },
    { book: 'josue', bookName: 'Josué', chapter: 1, verse: 8, label: 'Josué 1:8' },
    { book: 'josue', bookName: 'Josué', chapter: 1, verse: 9, label: 'Josué 1:9' },
    { book: 'josue', bookName: 'Josué', chapter: 3, verse: 5, label: 'Josué 3:5' },
    { book: 'josue', bookName: 'Josué', chapter: 10, verse: 14, label: 'Josué 10:14' },
    { book: 'josue', bookName: 'Josué', chapter: 21, verse: 45, label: 'Josué 21:45' },
    { book: 'josue', bookName: 'Josué', chapter: 23, verse: 11, label: 'Josué 23:11' },
    { book: 'josue', bookName: 'Josué', chapter: 24, verse: 15, label: 'Josué 24:15' },
    { book: 'jueces', bookName: 'Jueces', chapter: 2, verse: 1, label: 'Jueces 2:1' },
    { book: 'jueces', bookName: 'Jueces', chapter: 5, verse: 31, label: 'Jueces 5:31' },
    { book: 'jueces', bookName: 'Jueces', chapter: 6, verse: 12, label: 'Jueces 6:12' },
    { book: 'jueces', bookName: 'Jueces', chapter: 6, verse: 16, label: 'Jueces 6:16' },
    { book: 'jueces', bookName: 'Jueces', chapter: 13, verse: 24, label: 'Jueces 13:24' },
    { book: 'jueces', bookName: 'Jueces', chapter: 16, verse: 28, label: 'Jueces 16:28' },
    { book: 'jueces', bookName: 'Jueces', chapter: 21, verse: 25, label: 'Jueces 21:25' },
    { book: 'rut', bookName: 'Rut', chapter: 1, verse: 16, label: 'Rut 1:16' },
    { book: 'rut', bookName: 'Rut', chapter: 2, verse: 12, label: 'Rut 2:12' },
    { book: 'rut', bookName: 'Rut', chapter: 3, verse: 11, label: 'Rut 3:11' },
    { book: 'rut', bookName: 'Rut', chapter: 4, verse: 14, label: 'Rut 4:14' },
    { book: '1samuel', bookName: '1 Samuel', chapter: 1, verse: 27, label: '1 Samuel 1:27' },
    { book: '1samuel', bookName: '1 Samuel', chapter: 2, verse: 2, label: '1 Samuel 2:2' },
    { book: '1samuel', bookName: '1 Samuel', chapter: 3, verse: 10, label: '1 Samuel 3:10' },
    { book: '1samuel', bookName: '1 Samuel', chapter: 7, verse: 12, label: '1 Samuel 7:12' },
    { book: '1samuel', bookName: '1 Samuel', chapter: 12, verse: 24, label: '1 Samuel 12:24' },
    { book: '1samuel', bookName: '1 Samuel', chapter: 15, verse: 22, label: '1 Samuel 15:22' },
    { book: '1samuel', bookName: '1 Samuel', chapter: 16, verse: 7, label: '1 Samuel 16:7' },
    { book: '1samuel', bookName: '1 Samuel', chapter: 17, verse: 45, label: '1 Samuel 17:45' },
    { book: '1samuel', bookName: '1 Samuel', chapter: 17, verse: 47, label: '1 Samuel 17:47' },
    { book: '1samuel', bookName: '1 Samuel', chapter: 18, verse: 14, label: '1 Samuel 18:14' },
    { book: '1samuel', bookName: '1 Samuel', chapter: 24, verse: 10, label: '1 Samuel 24:10' },
    { book: '1samuel', bookName: '1 Samuel', chapter: 30, verse: 6, label: '1 Samuel 30:6' },
    { book: '2samuel', bookName: '2 Samuel', chapter: 5, verse: 10, label: '2 Samuel 5:10' },
    { book: '2samuel', bookName: '2 Samuel', chapter: 7, verse: 12, label: '2 Samuel 7:12' },
    { book: '2samuel', bookName: '2 Samuel', chapter: 7, verse: 22, label: '2 Samuel 7:22' },
    { book: '2samuel', bookName: '2 Samuel', chapter: 9, verse: 7, label: '2 Samuel 9:7' },
    { book: '2samuel', bookName: '2 Samuel', chapter: 12, verse: 13, label: '2 Samuel 12:13' },
    { book: '2samuel', bookName: '2 Samuel', chapter: 18, verse: 33, label: '2 Samuel 18:33' },
    { book: '2samuel', bookName: '2 Samuel', chapter: 22, verse: 2, label: '2 Samuel 22:2' },
    { book: '2samuel', bookName: '2 Samuel', chapter: 22, verse: 31, label: '2 Samuel 22:31' },
    { book: '2samuel', bookName: '2 Samuel', chapter: 23, verse: 5, label: '2 Samuel 23:5' },
    { book: '2samuel', bookName: '2 Samuel', chapter: 24, verse: 14, label: '2 Samuel 24:14' },
    { book: '1reyes', bookName: '1 Reyes', chapter: 2, verse: 3, label: '1 Reyes 2:3' },
    { book: '1reyes', bookName: '1 Reyes', chapter: 3, verse: 9, label: '1 Reyes 3:9' },
    { book: '1reyes', bookName: '1 Reyes', chapter: 3, verse: 12, label: '1 Reyes 3:12' },
    { book: '1reyes', bookName: '1 Reyes', chapter: 8, verse: 23, label: '1 Reyes 8:23' },
    { book: '1reyes', bookName: '1 Reyes', chapter: 8, verse: 56, label: '1 Reyes 8:56' },
    { book: '1reyes', bookName: '1 Reyes', chapter: 9, verse: 3, label: '1 Reyes 9:3' },
    { book: '1reyes', bookName: '1 Reyes', chapter: 11, verse: 38, label: '1 Reyes 11:38' },
    { book: '1reyes', bookName: '1 Reyes', chapter: 17, verse: 1, label: '1 Reyes 17:1' },
    { book: '1reyes', bookName: '1 Reyes', chapter: 18, verse: 21, label: '1 Reyes 18:21' },
    { book: '1reyes', bookName: '1 Reyes', chapter: 19, verse: 12, label: '1 Reyes 19:12' },
    { book: '2reyes', bookName: '2 Reyes', chapter: 2, verse: 9, label: '2 Reyes 2:9' },
    { book: '2reyes', bookName: '2 Reyes', chapter: 4, verse: 2, label: '2 Reyes 4:2' },
    { book: '2reyes', bookName: '2 Reyes', chapter: 5, verse: 14, label: '2 Reyes 5:14' },
    { book: '2reyes', bookName: '2 Reyes', chapter: 6, verse: 16, label: '2 Reyes 6:16' },
    { book: '2reyes', bookName: '2 Reyes', chapter: 17, verse: 39, label: '2 Reyes 17:39' },
    { book: '2reyes', bookName: '2 Reyes', chapter: 19, verse: 19, label: '2 Reyes 19:19' },
    { book: '2reyes', bookName: '2 Reyes', chapter: 20, verse: 5, label: '2 Reyes 20:5' },
    { book: '2reyes', bookName: '2 Reyes', chapter: 22, verse: 19, label: '2 Reyes 22:19' },
    { book: '2reyes', bookName: '2 Reyes', chapter: 23, verse: 3, label: '2 Reyes 23:3' },
    { book: '1cronicas', bookName: '1 Crónicas', chapter: 4, verse: 10, label: '1 Crónicas 4:10' },
    { book: '1cronicas', bookName: '1 Crónicas', chapter: 16, verse: 11, label: '1 Crónicas 16:11' },
    { book: '1cronicas', bookName: '1 Crónicas', chapter: 16, verse: 34, label: '1 Crónicas 16:34' },
    { book: '1cronicas', bookName: '1 Crónicas', chapter: 17, verse: 20, label: '1 Crónicas 17:20' },
    { book: '1cronicas', bookName: '1 Crónicas', chapter: 22, verse: 13, label: '1 Crónicas 22:13' },
    { book: '1cronicas', bookName: '1 Crónicas', chapter: 28, verse: 9, label: '1 Crónicas 28:9' },
    { book: '1cronicas', bookName: '1 Crónicas', chapter: 28, verse: 20, label: '1 Crónicas 28:20' },
    { book: '1cronicas', bookName: '1 Crónicas', chapter: 29, verse: 11, label: '1 Crónicas 29:11' },
    { book: '2cronicas', bookName: '2 Crónicas', chapter: 1, verse: 10, label: '2 Crónicas 1:10' },
    { book: '2cronicas', bookName: '2 Crónicas', chapter: 5, verse: 13, label: '2 Crónicas 5:13' },
    { book: '2cronicas', bookName: '2 Crónicas', chapter: 7, verse: 1, label: '2 Crónicas 7:1' },
    { book: '2cronicas', bookName: '2 Crónicas', chapter: 7, verse: 14, label: '2 Crónicas 7:14' },
    { book: '2cronicas', bookName: '2 Crónicas', chapter: 14, verse: 11, label: '2 Crónicas 14:11' },
    { book: '2cronicas', bookName: '2 Crónicas', chapter: 15, verse: 7, label: '2 Crónicas 15:7' },
    { book: '2cronicas', bookName: '2 Crónicas', chapter: 16, verse: 9, label: '2 Crónicas 16:9' },
    { book: '2cronicas', bookName: '2 Crónicas', chapter: 20, verse: 15, label: '2 Crónicas 20:15' },
    { book: '2cronicas', bookName: '2 Crónicas', chapter: 20, verse: 17, label: '2 Crónicas 20:17' },
    { book: '2cronicas', bookName: '2 Crónicas', chapter: 26, verse: 5, label: '2 Crónicas 26:5' },
    { book: '2cronicas', bookName: '2 Crónicas', chapter: 30, verse: 9, label: '2 Crónicas 30:9' },
    { book: '2cronicas', bookName: '2 Crónicas', chapter: 36, verse: 23, label: '2 Crónicas 36:23' },
    { book: 'esdras', bookName: 'Esdras', chapter: 1, verse: 3, label: 'Esdras 1:3' },
    { book: 'esdras', bookName: 'Esdras', chapter: 3, verse: 11, label: 'Esdras 3:11' },
    { book: 'esdras', bookName: 'Esdras', chapter: 7, verse: 10, label: 'Esdras 7:10' },
    { book: 'esdras', bookName: 'Esdras', chapter: 7, verse: 28, label: 'Esdras 7:28' },
    { book: 'esdras', bookName: 'Esdras', chapter: 8, verse: 22, label: 'Esdras 8:22' },
    { book: 'esdras', bookName: 'Esdras', chapter: 9, verse: 6, label: 'Esdras 9:6' },
    { book: 'esdras', bookName: 'Esdras', chapter: 10, verse: 4, label: 'Esdras 10:4' },
    { book: 'nehemias', bookName: 'Nehemías', chapter: 1, verse: 11, label: 'Nehemías 1:11' },
    { book: 'nehemias', bookName: 'Nehemías', chapter: 2, verse: 18, label: 'Nehemías 2:18' },
    { book: 'nehemias', bookName: 'Nehemías', chapter: 4, verse: 6, label: 'Nehemías 4:6' },
    { book: 'nehemias', bookName: 'Nehemías', chapter: 4, verse: 14, label: 'Nehemías 4:14' },
    { book: 'nehemias', bookName: 'Nehemías', chapter: 6, verse: 9, label: 'Nehemías 6:9' },
    { book: 'nehemias', bookName: 'Nehemías', chapter: 8, verse: 10, label: 'Nehemías 8:10' },
    { book: 'nehemias', bookName: 'Nehemías', chapter: 9, verse: 17, label: 'Nehemías 9:17' },
    { book: 'nehemias', bookName: 'Nehemías', chapter: 13, verse: 31, label: 'Nehemías 13:31' },
    { book: 'ester', bookName: 'Ester', chapter: 2, verse: 17, label: 'Ester 2:17' },
    { book: 'ester', bookName: 'Ester', chapter: 4, verse: 14, label: 'Ester 4:14' },
    { book: 'ester', bookName: 'Ester', chapter: 4, verse: 16, label: 'Ester 4:16' },
    { book: 'ester', bookName: 'Ester', chapter: 5, verse: 2, label: 'Ester 5:2' },
    { book: 'ester', bookName: 'Ester', chapter: 7, verse: 3, label: 'Ester 7:3' },
    { book: 'ester', bookName: 'Ester', chapter: 8, verse: 16, label: 'Ester 8:16' },
    { book: 'ester', bookName: 'Ester', chapter: 9, verse: 22, label: 'Ester 9:22' },
    { book: 'job', bookName: 'Job', chapter: 1, verse: 21, label: 'Job 1:21' },
    { book: 'job', bookName: 'Job', chapter: 2, verse: 10, label: 'Job 2:10' },
    { book: 'job', bookName: 'Job', chapter: 5, verse: 17, label: 'Job 5:17' },
    { book: 'job', bookName: 'Job', chapter: 11, verse: 7, label: 'Job 11:7' },
    { book: 'job', bookName: 'Job', chapter: 19, verse: 25, label: 'Job 19:25' },
    { book: 'job', bookName: 'Job', chapter: 23, verse: 10, label: 'Job 23:10' },
    { book: 'job', bookName: 'Job', chapter: 28, verse: 28, label: 'Job 28:28' },
    { book: 'job', bookName: 'Job', chapter: 33, verse: 4, label: 'Job 33:4' },
    { book: 'job', bookName: 'Job', chapter: 36, verse: 5, label: 'Job 36:5' },
    { book: 'job', bookName: 'Job', chapter: 37, verse: 5, label: 'Job 37:5' },
    { book: 'job', bookName: 'Job', chapter: 38, verse: 4, label: 'Job 38:4' },
    { book: 'job', bookName: 'Job', chapter: 40, verse: 2, label: 'Job 40:2' },
    { book: 'job', bookName: 'Job', chapter: 42, verse: 2, label: 'Job 42:2' },
    { book: 'job', bookName: 'Job', chapter: 42, verse: 5, label: 'Job 42:5' },
    { book: 'salmos', bookName: 'Salmos', chapter: 1, verse: 1, label: 'Salmos 1:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 1, verse: 2, label: 'Salmos 1:2' },
    { book: 'salmos', bookName: 'Salmos', chapter: 1, verse: 3, label: 'Salmos 1:3' },
    { book: 'salmos', bookName: 'Salmos', chapter: 4, verse: 8, label: 'Salmos 4:8' },
    { book: 'salmos', bookName: 'Salmos', chapter: 5, verse: 3, label: 'Salmos 5:3' },
    { book: 'salmos', bookName: 'Salmos', chapter: 8, verse: 1, label: 'Salmos 8:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 9, verse: 1, label: 'Salmos 9:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 16, verse: 8, label: 'Salmos 16:8' },
    { book: 'salmos', bookName: 'Salmos', chapter: 18, verse: 2, label: 'Salmos 18:2' },
    { book: 'salmos', bookName: 'Salmos', chapter: 19, verse: 1, label: 'Salmos 19:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 19, verse: 14, label: 'Salmos 19:14' },
    { book: 'salmos', bookName: 'Salmos', chapter: 20, verse: 7, label: 'Salmos 20:7' },
    { book: 'salmos', bookName: 'Salmos', chapter: 23, verse: 1, label: 'Salmos 23:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 23, verse: 4, label: 'Salmos 23:4' },
    { book: 'salmos', bookName: 'Salmos', chapter: 23, verse: 6, label: 'Salmos 23:6' },
    { book: 'salmos', bookName: 'Salmos', chapter: 24, verse: 1, label: 'Salmos 24:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 25, verse: 4, label: 'Salmos 25:4' },
    { book: 'salmos', bookName: 'Salmos', chapter: 27, verse: 1, label: 'Salmos 27:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 27, verse: 4, label: 'Salmos 27:4' },
    { book: 'salmos', bookName: 'Salmos', chapter: 27, verse: 14, label: 'Salmos 27:14' },
    { book: 'salmos', bookName: 'Salmos', chapter: 29, verse: 11, label: 'Salmos 29:11' },
    { book: 'salmos', bookName: 'Salmos', chapter: 30, verse: 5, label: 'Salmos 30:5' },
    { book: 'salmos', bookName: 'Salmos', chapter: 31, verse: 24, label: 'Salmos 31:24' },
    { book: 'salmos', bookName: 'Salmos', chapter: 32, verse: 7, label: 'Salmos 32:7' },
    { book: 'salmos', bookName: 'Salmos', chapter: 33, verse: 12, label: 'Salmos 33:12' },
    { book: 'salmos', bookName: 'Salmos', chapter: 34, verse: 8, label: 'Salmos 34:8' },
    { book: 'salmos', bookName: 'Salmos', chapter: 34, verse: 18, label: 'Salmos 34:18' },
    { book: 'salmos', bookName: 'Salmos', chapter: 36, verse: 7, label: 'Salmos 36:7' },
    { book: 'salmos', bookName: 'Salmos', chapter: 37, verse: 4, label: 'Salmos 37:4' },
    { book: 'salmos', bookName: 'Salmos', chapter: 37, verse: 5, label: 'Salmos 37:5' },
    { book: 'salmos', bookName: 'Salmos', chapter: 37, verse: 23, label: 'Salmos 37:23' },
    { book: 'salmos', bookName: 'Salmos', chapter: 40, verse: 1, label: 'Salmos 40:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 42, verse: 1, label: 'Salmos 42:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 42, verse: 11, label: 'Salmos 42:11' },
    { book: 'salmos', bookName: 'Salmos', chapter: 46, verse: 1, label: 'Salmos 46:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 46, verse: 10, label: 'Salmos 46:10' },
    { book: 'salmos', bookName: 'Salmos', chapter: 48, verse: 14, label: 'Salmos 48:14' },
    { book: 'salmos', bookName: 'Salmos', chapter: 51, verse: 10, label: 'Salmos 51:10' },
    { book: 'salmos', bookName: 'Salmos', chapter: 55, verse: 22, label: 'Salmos 55:22' },
    { book: 'salmos', bookName: 'Salmos', chapter: 56, verse: 3, label: 'Salmos 56:3' },
    { book: 'salmos', bookName: 'Salmos', chapter: 62, verse: 1, label: 'Salmos 62:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 63, verse: 1, label: 'Salmos 63:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 66, verse: 18, label: 'Salmos 66:18' },
    { book: 'salmos', bookName: 'Salmos', chapter: 68, verse: 19, label: 'Salmos 68:19' },
    { book: 'salmos', bookName: 'Salmos', chapter: 69, verse: 30, label: 'Salmos 69:30' },
    { book: 'salmos', bookName: 'Salmos', chapter: 71, verse: 18, label: 'Salmos 71:18' },
    { book: 'salmos', bookName: 'Salmos', chapter: 73, verse: 25, label: 'Salmos 73:25' },
    { book: 'salmos', bookName: 'Salmos', chapter: 77, verse: 14, label: 'Salmos 77:14' },
    { book: 'salmos', bookName: 'Salmos', chapter: 84, verse: 10, label: 'Salmos 84:10' },
    { book: 'salmos', bookName: 'Salmos', chapter: 86, verse: 15, label: 'Salmos 86:15' },
    { book: 'salmos', bookName: 'Salmos', chapter: 89, verse: 1, label: 'Salmos 89:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 90, verse: 12, label: 'Salmos 90:12' },
    { book: 'salmos', bookName: 'Salmos', chapter: 91, verse: 1, label: 'Salmos 91:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 91, verse: 2, label: 'Salmos 91:2' },
    { book: 'salmos', bookName: 'Salmos', chapter: 91, verse: 11, label: 'Salmos 91:11' },
    { book: 'salmos', bookName: 'Salmos', chapter: 92, verse: 1, label: 'Salmos 92:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 94, verse: 18, label: 'Salmos 94:18' },
    { book: 'salmos', bookName: 'Salmos', chapter: 95, verse: 6, label: 'Salmos 95:6' },
    { book: 'salmos', bookName: 'Salmos', chapter: 100, verse: 3, label: 'Salmos 100:3' },
    { book: 'salmos', bookName: 'Salmos', chapter: 100, verse: 5, label: 'Salmos 100:5' },
    { book: 'salmos', bookName: 'Salmos', chapter: 103, verse: 1, label: 'Salmos 103:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 103, verse: 8, label: 'Salmos 103:8' },
    { book: 'salmos', bookName: 'Salmos', chapter: 103, verse: 12, label: 'Salmos 103:12' },
    { book: 'salmos', bookName: 'Salmos', chapter: 104, verse: 24, label: 'Salmos 104:24' },
    { book: 'salmos', bookName: 'Salmos', chapter: 105, verse: 1, label: 'Salmos 105:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 107, verse: 1, label: 'Salmos 107:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 111, verse: 10, label: 'Salmos 111:10' },
    { book: 'salmos', bookName: 'Salmos', chapter: 112, verse: 1, label: 'Salmos 112:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 116, verse: 1, label: 'Salmos 116:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 117, verse: 1, label: 'Salmos 117:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 117, verse: 2, label: 'Salmos 117:2' },
    { book: 'salmos', bookName: 'Salmos', chapter: 118, verse: 1, label: 'Salmos 118:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 118, verse: 24, label: 'Salmos 118:24' },
    { book: 'salmos', bookName: 'Salmos', chapter: 119, verse: 9, label: 'Salmos 119:9' },
    { book: 'salmos', bookName: 'Salmos', chapter: 119, verse: 11, label: 'Salmos 119:11' },
    { book: 'salmos', bookName: 'Salmos', chapter: 119, verse: 18, label: 'Salmos 119:18' },
    { book: 'salmos', bookName: 'Salmos', chapter: 119, verse: 105, label: 'Salmos 119:105' },
    { book: 'salmos', bookName: 'Salmos', chapter: 119, verse: 114, label: 'Salmos 119:114' },
    { book: 'salmos', bookName: 'Salmos', chapter: 119, verse: 165, label: 'Salmos 119:165' },
    { book: 'salmos', bookName: 'Salmos', chapter: 121, verse: 1, label: 'Salmos 121:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 121, verse: 2, label: 'Salmos 121:2' },
    { book: 'salmos', bookName: 'Salmos', chapter: 121, verse: 7, label: 'Salmos 121:7' },
    { book: 'salmos', bookName: 'Salmos', chapter: 122, verse: 1, label: 'Salmos 122:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 124, verse: 8, label: 'Salmos 124:8' },
    { book: 'salmos', bookName: 'Salmos', chapter: 126, verse: 3, label: 'Salmos 126:3' },
    { book: 'salmos', bookName: 'Salmos', chapter: 127, verse: 1, label: 'Salmos 127:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 128, verse: 1, label: 'Salmos 128:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 130, verse: 5, label: 'Salmos 130:5' },
    { book: 'salmos', bookName: 'Salmos', chapter: 133, verse: 1, label: 'Salmos 133:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 136, verse: 1, label: 'Salmos 136:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 138, verse: 3, label: 'Salmos 138:3' },
    { book: 'salmos', bookName: 'Salmos', chapter: 139, verse: 1, label: 'Salmos 139:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 139, verse: 14, label: 'Salmos 139:14' },
    { book: 'salmos', bookName: 'Salmos', chapter: 139, verse: 23, label: 'Salmos 139:23' },
    { book: 'salmos', bookName: 'Salmos', chapter: 140, verse: 7, label: 'Salmos 140:7' },
    { book: 'salmos', bookName: 'Salmos', chapter: 141, verse: 3, label: 'Salmos 141:3' },
    { book: 'salmos', bookName: 'Salmos', chapter: 143, verse: 8, label: 'Salmos 143:8' },
    { book: 'salmos', bookName: 'Salmos', chapter: 144, verse: 1, label: 'Salmos 144:1' },
    { book: 'salmos', bookName: 'Salmos', chapter: 145, verse: 8, label: 'Salmos 145:8' },
    { book: 'salmos', bookName: 'Salmos', chapter: 145, verse: 18, label: 'Salmos 145:18' },
    { book: 'salmos', bookName: 'Salmos', chapter: 146, verse: 5, label: 'Salmos 146:5' },
    { book: 'salmos', bookName: 'Salmos', chapter: 147, verse: 3, label: 'Salmos 147:3' },
    { book: 'salmos', bookName: 'Salmos', chapter: 148, verse: 13, label: 'Salmos 148:13' },
    { book: 'salmos', bookName: 'Salmos', chapter: 149, verse: 4, label: 'Salmos 149:4' },
    { book: 'salmos', bookName: 'Salmos', chapter: 150, verse: 6, label: 'Salmos 150:6' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 1, verse: 7, label: 'Proverbios 1:7' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 2, verse: 6, label: 'Proverbios 2:6' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 3, verse: 5, label: 'Proverbios 3:5' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 3, verse: 6, label: 'Proverbios 3:6' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 3, verse: 9, label: 'Proverbios 3:9' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 4, verse: 23, label: 'Proverbios 4:23' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 8, verse: 11, label: 'Proverbios 8:11' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 9, verse: 10, label: 'Proverbios 9:10' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 10, verse: 22, label: 'Proverbios 10:22' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 11, verse: 2, label: 'Proverbios 11:2' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 13, verse: 20, label: 'Proverbios 13:20' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 14, verse: 26, label: 'Proverbios 14:26' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 15, verse: 1, label: 'Proverbios 15:1' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 15, verse: 3, label: 'Proverbios 15:3' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 16, verse: 3, label: 'Proverbios 16:3' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 16, verse: 9, label: 'Proverbios 16:9' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 17, verse: 17, label: 'Proverbios 17:17' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 18, verse: 10, label: 'Proverbios 18:10' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 18, verse: 21, label: 'Proverbios 18:21' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 19, verse: 21, label: 'Proverbios 19:21' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 20, verse: 5, label: 'Proverbios 20:5' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 21, verse: 21, label: 'Proverbios 21:21' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 22, verse: 1, label: 'Proverbios 22:1' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 22, verse: 6, label: 'Proverbios 22:6' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 27, verse: 1, label: 'Proverbios 27:1' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 28, verse: 13, label: 'Proverbios 28:13' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 29, verse: 25, label: 'Proverbios 29:25' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 30, verse: 5, label: 'Proverbios 30:5' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 31, verse: 10, label: 'Proverbios 31:10' },
    { book: 'proverbios', bookName: 'Proverbios', chapter: 31, verse: 30, label: 'Proverbios 31:30' },
    { book: 'eclesiastes', bookName: 'Eclesiastés', chapter: 3, verse: 1, label: 'Eclesiastés 3:1' },
    { book: 'eclesiastes', bookName: 'Eclesiastés', chapter: 3, verse: 11, label: 'Eclesiastés 3:11' },
    { book: 'eclesiastes', bookName: 'Eclesiastés', chapter: 4, verse: 9, label: 'Eclesiastés 4:9' },
    { book: 'eclesiastes', bookName: 'Eclesiastés', chapter: 5, verse: 2, label: 'Eclesiastés 5:2' },
    { book: 'eclesiastes', bookName: 'Eclesiastés', chapter: 7, verse: 8, label: 'Eclesiastés 7:8' },
    { book: 'eclesiastes', bookName: 'Eclesiastés', chapter: 9, verse: 10, label: 'Eclesiastés 9:10' },
    { book: 'eclesiastes', bookName: 'Eclesiastés', chapter: 11, verse: 1, label: 'Eclesiastés 11:1' },
    { book: 'eclesiastes', bookName: 'Eclesiastés', chapter: 12, verse: 1, label: 'Eclesiastés 12:1' },
    { book: 'eclesiastes', bookName: 'Eclesiastés', chapter: 12, verse: 13, label: 'Eclesiastés 12:13' },
    { book: 'cantares', bookName: 'Cantares', chapter: 2, verse: 4, label: 'Cantares 2:4' },
    { book: 'cantares', bookName: 'Cantares', chapter: 2, verse: 16, label: 'Cantares 2:16' },
    { book: 'cantares', bookName: 'Cantares', chapter: 4, verse: 7, label: 'Cantares 4:7' },
    { book: 'cantares', bookName: 'Cantares', chapter: 6, verse: 3, label: 'Cantares 6:3' },
    { book: 'cantares', bookName: 'Cantares', chapter: 8, verse: 6, label: 'Cantares 8:6' },
    { book: 'cantares', bookName: 'Cantares', chapter: 8, verse: 7, label: 'Cantares 8:7' },
    { book: 'isaias', bookName: 'Isaías', chapter: 1, verse: 18, label: 'Isaías 1:18' },
    { book: 'isaias', bookName: 'Isaías', chapter: 6, verse: 3, label: 'Isaías 6:3' },
    { book: 'isaias', bookName: 'Isaías', chapter: 6, verse: 8, label: 'Isaías 6:8' },
    { book: 'isaias', bookName: 'Isaías', chapter: 7, verse: 14, label: 'Isaías 7:14' },
    { book: 'isaias', bookName: 'Isaías', chapter: 9, verse: 6, label: 'Isaías 9:6' },
    { book: 'isaias', bookName: 'Isaías', chapter: 11, verse: 2, label: 'Isaías 11:2' },
    { book: 'isaias', bookName: 'Isaías', chapter: 12, verse: 2, label: 'Isaías 12:2' },
    { book: 'isaias', bookName: 'Isaías', chapter: 25, verse: 1, label: 'Isaías 25:1' },
    { book: 'isaias', bookName: 'Isaías', chapter: 26, verse: 3, label: 'Isaías 26:3' },
    { book: 'isaias', bookName: 'Isaías', chapter: 26, verse: 4, label: 'Isaías 26:4' },
    { book: 'isaias', bookName: 'Isaías', chapter: 30, verse: 15, label: 'Isaías 30:15' },
    { book: 'isaias', bookName: 'Isaías', chapter: 33, verse: 22, label: 'Isaías 33:22' },
    { book: 'isaias', bookName: 'Isaías', chapter: 35, verse: 4, label: 'Isaías 35:4' },
    { book: 'isaias', bookName: 'Isaías', chapter: 40, verse: 3, label: 'Isaías 40:3' },
    { book: 'isaias', bookName: 'Isaías', chapter: 40, verse: 8, label: 'Isaías 40:8' },
    { book: 'isaias', bookName: 'Isaías', chapter: 40, verse: 11, label: 'Isaías 40:11' },
    { book: 'isaias', bookName: 'Isaías', chapter: 40, verse: 28, label: 'Isaías 40:28' },
    { book: 'isaias', bookName: 'Isaías', chapter: 40, verse: 29, label: 'Isaías 40:29' },
    { book: 'isaias', bookName: 'Isaías', chapter: 40, verse: 31, label: 'Isaías 40:31' },
    { book: 'isaias', bookName: 'Isaías', chapter: 41, verse: 10, label: 'Isaías 41:10' },
    { book: 'isaias', bookName: 'Isaías', chapter: 41, verse: 13, label: 'Isaías 41:13' },
    { book: 'isaias', bookName: 'Isaías', chapter: 42, verse: 6, label: 'Isaías 42:6' },
    { book: 'isaias', bookName: 'Isaías', chapter: 43, verse: 1, label: 'Isaías 43:1' },
    { book: 'isaias', bookName: 'Isaías', chapter: 43, verse: 2, label: 'Isaías 43:2' },
    { book: 'isaias', bookName: 'Isaías', chapter: 43, verse: 19, label: 'Isaías 43:19' },
    { book: 'isaias', bookName: 'Isaías', chapter: 44, verse: 22, label: 'Isaías 44:22' },
    { book: 'isaias', bookName: 'Isaías', chapter: 45, verse: 22, label: 'Isaías 45:22' },
    { book: 'isaias', bookName: 'Isaías', chapter: 46, verse: 4, label: 'Isaías 46:4' },
    { book: 'isaias', bookName: 'Isaías', chapter: 48, verse: 17, label: 'Isaías 48:17' },
    { book: 'isaias', bookName: 'Isaías', chapter: 49, verse: 15, label: 'Isaías 49:15' },
    { book: 'isaias', bookName: 'Isaías', chapter: 50, verse: 4, label: 'Isaías 50:4' },
    { book: 'isaias', bookName: 'Isaías', chapter: 53, verse: 3, label: 'Isaías 53:3' },
    { book: 'isaias', bookName: 'Isaías', chapter: 53, verse: 4, label: 'Isaías 53:4' },
    { book: 'isaias', bookName: 'Isaías', chapter: 53, verse: 5, label: 'Isaías 53:5' },
    { book: 'isaias', bookName: 'Isaías', chapter: 53, verse: 6, label: 'Isaías 53:6' },
    { book: 'isaias', bookName: 'Isaías', chapter: 54, verse: 10, label: 'Isaías 54:10' },
    { book: 'isaias', bookName: 'Isaías', chapter: 55, verse: 1, label: 'Isaías 55:1' },
    { book: 'isaias', bookName: 'Isaías', chapter: 55, verse: 6, label: 'Isaías 55:6' },
    { book: 'isaias', bookName: 'Isaías', chapter: 55, verse: 8, label: 'Isaías 55:8' },
    { book: 'isaias', bookName: 'Isaías', chapter: 57, verse: 15, label: 'Isaías 57:15' },
    { book: 'isaias', bookName: 'Isaías', chapter: 58, verse: 11, label: 'Isaías 58:11' },
    { book: 'isaias', bookName: 'Isaías', chapter: 59, verse: 1, label: 'Isaías 59:1' },
    { book: 'isaias', bookName: 'Isaías', chapter: 60, verse: 1, label: 'Isaías 60:1' },
    { book: 'isaias', bookName: 'Isaías', chapter: 61, verse: 1, label: 'Isaías 61:1' },
    { book: 'isaias', bookName: 'Isaías', chapter: 61, verse: 3, label: 'Isaías 61:3' },
    { book: 'isaias', bookName: 'Isaías', chapter: 64, verse: 8, label: 'Isaías 64:8' },
    { book: 'isaias', bookName: 'Isaías', chapter: 65, verse: 24, label: 'Isaías 65:24' },
    { book: 'isaias', bookName: 'Isaías', chapter: 66, verse: 13, label: 'Isaías 66:13' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 1, verse: 5, label: 'Jeremías 1:5' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 1, verse: 8, label: 'Jeremías 1:8' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 1, verse: 19, label: 'Jeremías 1:19' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 9, verse: 23, label: 'Jeremías 9:23' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 10, verse: 12, label: 'Jeremías 10:12' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 15, verse: 16, label: 'Jeremías 15:16' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 17, verse: 7, label: 'Jeremías 17:7' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 17, verse: 8, label: 'Jeremías 17:8' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 17, verse: 14, label: 'Jeremías 17:14' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 20, verse: 11, label: 'Jeremías 20:11' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 23, verse: 6, label: 'Jeremías 23:6' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 29, verse: 11, label: 'Jeremías 29:11' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 29, verse: 13, label: 'Jeremías 29:13' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 30, verse: 17, label: 'Jeremías 30:17' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 31, verse: 3, label: 'Jeremías 31:3' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 31, verse: 33, label: 'Jeremías 31:33' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 32, verse: 17, label: 'Jeremías 32:17' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 32, verse: 27, label: 'Jeremías 32:27' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 33, verse: 3, label: 'Jeremías 33:3' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 33, verse: 6, label: 'Jeremías 33:6' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 39, verse: 18, label: 'Jeremías 39:18' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 42, verse: 11, label: 'Jeremías 42:11' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 46, verse: 27, label: 'Jeremías 46:27' },
    { book: 'jeremias', bookName: 'Jeremías', chapter: 51, verse: 15, label: 'Jeremías 51:15' },
    { book: 'lamentaciones', bookName: 'Lamentaciones', chapter: 3, verse: 22, label: 'Lamentaciones 3:22' },
    { book: 'lamentaciones', bookName: 'Lamentaciones', chapter: 3, verse: 23, label: 'Lamentaciones 3:23' },
    { book: 'lamentaciones', bookName: 'Lamentaciones', chapter: 3, verse: 24, label: 'Lamentaciones 3:24' },
    { book: 'lamentaciones', bookName: 'Lamentaciones', chapter: 3, verse: 25, label: 'Lamentaciones 3:25' },
    { book: 'lamentaciones', bookName: 'Lamentaciones', chapter: 3, verse: 40, label: 'Lamentaciones 3:40' },
    { book: 'lamentaciones', bookName: 'Lamentaciones', chapter: 5, verse: 21, label: 'Lamentaciones 5:21' },
    { book: 'ezequiel', bookName: 'Ezequiel', chapter: 1, verse: 28, label: 'Ezequiel 1:28' },
    { book: 'ezequiel', bookName: 'Ezequiel', chapter: 3, verse: 17, label: 'Ezequiel 3:17' },
    { book: 'ezequiel', bookName: 'Ezequiel', chapter: 11, verse: 19, label: 'Ezequiel 11:19' },
    { book: 'ezequiel', bookName: 'Ezequiel', chapter: 18, verse: 32, label: 'Ezequiel 18:32' },
    { book: 'ezequiel', bookName: 'Ezequiel', chapter: 33, verse: 11, label: 'Ezequiel 33:11' },
    { book: 'ezequiel', bookName: 'Ezequiel', chapter: 34, verse: 11, label: 'Ezequiel 34:11' },
    { book: 'ezequiel', bookName: 'Ezequiel', chapter: 36, verse: 26, label: 'Ezequiel 36:26' },
    { book: 'ezequiel', bookName: 'Ezequiel', chapter: 37, verse: 5, label: 'Ezequiel 37:5' },
    { book: 'ezequiel', bookName: 'Ezequiel', chapter: 37, verse: 14, label: 'Ezequiel 37:14' },
    { book: 'ezequiel', bookName: 'Ezequiel', chapter: 43, verse: 2, label: 'Ezequiel 43:2' },
    { book: 'daniel', bookName: 'Daniel', chapter: 1, verse: 8, label: 'Daniel 1:8' },
    { book: 'daniel', bookName: 'Daniel', chapter: 2, verse: 20, label: 'Daniel 2:20' },
    { book: 'daniel', bookName: 'Daniel', chapter: 2, verse: 22, label: 'Daniel 2:22' },
    { book: 'daniel', bookName: 'Daniel', chapter: 3, verse: 17, label: 'Daniel 3:17' },
    { book: 'daniel', bookName: 'Daniel', chapter: 6, verse: 22, label: 'Daniel 6:22' },
    { book: 'daniel', bookName: 'Daniel', chapter: 6, verse: 26, label: 'Daniel 6:26' },
    { book: 'daniel', bookName: 'Daniel', chapter: 7, verse: 14, label: 'Daniel 7:14' },
    { book: 'daniel', bookName: 'Daniel', chapter: 9, verse: 9, label: 'Daniel 9:9' },
    { book: 'daniel', bookName: 'Daniel', chapter: 10, verse: 12, label: 'Daniel 10:12' },
    { book: 'daniel', bookName: 'Daniel', chapter: 10, verse: 19, label: 'Daniel 10:19' },
    { book: 'daniel', bookName: 'Daniel', chapter: 12, verse: 3, label: 'Daniel 12:3' },
    { book: 'oseas', bookName: 'Oseas', chapter: 2, verse: 19, label: 'Oseas 2:19' },
    { book: 'oseas', bookName: 'Oseas', chapter: 6, verse: 1, label: 'Oseas 6:1' },
    { book: 'oseas', bookName: 'Oseas', chapter: 6, verse: 3, label: 'Oseas 6:3' },
    { book: 'oseas', bookName: 'Oseas', chapter: 10, verse: 12, label: 'Oseas 10:12' },
    { book: 'oseas', bookName: 'Oseas', chapter: 11, verse: 1, label: 'Oseas 11:1' },
    { book: 'oseas', bookName: 'Oseas', chapter: 13, verse: 14, label: 'Oseas 13:14' },
    { book: 'oseas', bookName: 'Oseas', chapter: 14, verse: 9, label: 'Oseas 14:9' },
    { book: 'joel', bookName: 'Joel', chapter: 2, verse: 12, label: 'Joel 2:12' },
    { book: 'joel', bookName: 'Joel', chapter: 2, verse: 13, label: 'Joel 2:13' },
    { book: 'joel', bookName: 'Joel', chapter: 2, verse: 25, label: 'Joel 2:25' },
    { book: 'joel', bookName: 'Joel', chapter: 2, verse: 28, label: 'Joel 2:28' },
    { book: 'joel', bookName: 'Joel', chapter: 3, verse: 10, label: 'Joel 3:10' },
    { book: 'amos', bookName: 'Amós', chapter: 3, verse: 7, label: 'Amós 3:7' },
    { book: 'amos', bookName: 'Amós', chapter: 4, verse: 13, label: 'Amós 4:13' },
    { book: 'amos', bookName: 'Amós', chapter: 5, verse: 4, label: 'Amós 5:4' },
    { book: 'amos', bookName: 'Amós', chapter: 5, verse: 24, label: 'Amós 5:24' },
    { book: 'amos', bookName: 'Amós', chapter: 9, verse: 11, label: 'Amós 9:11' },
    { book: 'abdias', bookName: 'Abdías', chapter: 1, verse: 15, label: 'Abdías 1:15' },
    { book: 'abdias', bookName: 'Abdías', chapter: 1, verse: 21, label: 'Abdías 1:21' },
    { book: 'jonas', bookName: 'Jonás', chapter: 1, verse: 17, label: 'Jonás 1:17' },
    { book: 'jonas', bookName: 'Jonás', chapter: 2, verse: 2, label: 'Jonás 2:2' },
    { book: 'jonas', bookName: 'Jonás', chapter: 2, verse: 9, label: 'Jonás 2:9' },
    { book: 'jonas', bookName: 'Jonás', chapter: 3, verse: 10, label: 'Jonás 3:10' },
    { book: 'jonas', bookName: 'Jonás', chapter: 4, verse: 11, label: 'Jonás 4:11' },
    { book: 'miqueas', bookName: 'Miqueas', chapter: 4, verse: 3, label: 'Miqueas 4:3' },
    { book: 'miqueas', bookName: 'Miqueas', chapter: 5, verse: 2, label: 'Miqueas 5:2' },
    { book: 'miqueas', bookName: 'Miqueas', chapter: 6, verse: 8, label: 'Miqueas 6:8' },
    { book: 'miqueas', bookName: 'Miqueas', chapter: 7, verse: 7, label: 'Miqueas 7:7' },
    { book: 'miqueas', bookName: 'Miqueas', chapter: 7, verse: 18, label: 'Miqueas 7:18' },
    { book: 'miqueas', bookName: 'Miqueas', chapter: 7, verse: 19, label: 'Miqueas 7:19' },
    { book: 'nahum', bookName: 'Nahum', chapter: 1, verse: 3, label: 'Nahum 1:3' },
    { book: 'nahum', bookName: 'Nahum', chapter: 1, verse: 7, label: 'Nahum 1:7' },
    { book: 'nahum', bookName: 'Nahum', chapter: 1, verse: 15, label: 'Nahum 1:15' },
    { book: 'habacuc', bookName: 'Habacuc', chapter: 1, verse: 5, label: 'Habacuc 1:5' },
    { book: 'habacuc', bookName: 'Habacuc', chapter: 2, verse: 4, label: 'Habacuc 2:4' },
    { book: 'habacuc', bookName: 'Habacuc', chapter: 2, verse: 14, label: 'Habacuc 2:14' },
    { book: 'habacuc', bookName: 'Habacuc', chapter: 3, verse: 17, label: 'Habacuc 3:17' },
    { book: 'habacuc', bookName: 'Habacuc', chapter: 3, verse: 18, label: 'Habacuc 3:18' },
    { book: 'habacuc', bookName: 'Habacuc', chapter: 3, verse: 19, label: 'Habacuc 3:19' },
    { book: 'sofonias', bookName: 'Sofonías', chapter: 1, verse: 7, label: 'Sofonías 1:7' },
    { book: 'sofonias', bookName: 'Sofonías', chapter: 2, verse: 3, label: 'Sofonías 2:3' },
    { book: 'sofonias', bookName: 'Sofonías', chapter: 3, verse: 12, label: 'Sofonías 3:12' },
    { book: 'sofonias', bookName: 'Sofonías', chapter: 3, verse: 17, label: 'Sofonías 3:17' },
    { book: 'hageo', bookName: 'Hageo', chapter: 1, verse: 7, label: 'Hageo 1:7' },
    { book: 'hageo', bookName: 'Hageo', chapter: 1, verse: 13, label: 'Hageo 1:13' },
    { book: 'hageo', bookName: 'Hageo', chapter: 2, verse: 4, label: 'Hageo 2:4' },
    { book: 'hageo', bookName: 'Hageo', chapter: 2, verse: 5, label: 'Hageo 2:5' },
    { book: 'hageo', bookName: 'Hageo', chapter: 2, verse: 9, label: 'Hageo 2:9' },
    { book: 'zacarias', bookName: 'Zacarías', chapter: 1, verse: 3, label: 'Zacarías 1:3' },
    { book: 'zacarias', bookName: 'Zacarías', chapter: 2, verse: 8, label: 'Zacarías 2:8' },
    { book: 'zacarias', bookName: 'Zacarías', chapter: 3, verse: 2, label: 'Zacarías 3:2' },
    { book: 'zacarias', bookName: 'Zacarías', chapter: 4, verse: 6, label: 'Zacarías 4:6' },
    { book: 'zacarias', bookName: 'Zacarías', chapter: 7, verse: 9, label: 'Zacarías 7:9' },
    { book: 'zacarias', bookName: 'Zacarías', chapter: 8, verse: 16, label: 'Zacarías 8:16' },
    { book: 'zacarias', bookName: 'Zacarías', chapter: 9, verse: 9, label: 'Zacarías 9:9' },
    { book: 'zacarias', bookName: 'Zacarías', chapter: 9, verse: 12, label: 'Zacarías 9:12' },
    { book: 'zacarias', bookName: 'Zacarías', chapter: 10, verse: 6, label: 'Zacarías 10:6' },
    { book: 'zacarias', bookName: 'Zacarías', chapter: 12, verse: 10, label: 'Zacarías 12:10' },
    { book: 'zacarias', bookName: 'Zacarías', chapter: 13, verse: 9, label: 'Zacarías 13:9' },
    { book: 'zacarias', bookName: 'Zacarías', chapter: 14, verse: 9, label: 'Zacarías 14:9' },
    { book: 'malaquias', bookName: 'Malaquías', chapter: 1, verse: 11, label: 'Malaquías 1:11' },
    { book: 'malaquias', bookName: 'Malaquías', chapter: 2, verse: 2, label: 'Malaquías 2:2' },
    { book: 'malaquias', bookName: 'Malaquías', chapter: 3, verse: 1, label: 'Malaquías 3:1' },
    { book: 'malaquias', bookName: 'Malaquías', chapter: 3, verse: 6, label: 'Malaquías 3:6' },
    { book: 'malaquias', bookName: 'Malaquías', chapter: 3, verse: 10, label: 'Malaquías 3:10' },
    { book: 'malaquias', bookName: 'Malaquías', chapter: 3, verse: 16, label: 'Malaquías 3:16' },
    { book: 'malaquias', bookName: 'Malaquías', chapter: 4, verse: 2, label: 'Malaquías 4:2' },
    { book: 'mateo', bookName: 'Mateo', chapter: 1, verse: 21, label: 'Mateo 1:21' },
    { book: 'mateo', bookName: 'Mateo', chapter: 2, verse: 2, label: 'Mateo 2:2' },
    { book: 'mateo', bookName: 'Mateo', chapter: 4, verse: 4, label: 'Mateo 4:4' },
    { book: 'mateo', bookName: 'Mateo', chapter: 4, verse: 19, label: 'Mateo 4:19' },
    { book: 'mateo', bookName: 'Mateo', chapter: 5, verse: 3, label: 'Mateo 5:3' },
    { book: 'mateo', bookName: 'Mateo', chapter: 5, verse: 8, label: 'Mateo 5:8' },
    { book: 'mateo', bookName: 'Mateo', chapter: 5, verse: 14, label: 'Mateo 5:14' },
    { book: 'mateo', bookName: 'Mateo', chapter: 5, verse: 16, label: 'Mateo 5:16' },
    { book: 'mateo', bookName: 'Mateo', chapter: 5, verse: 44, label: 'Mateo 5:44' },
    { book: 'mateo', bookName: 'Mateo', chapter: 6, verse: 9, label: 'Mateo 6:9' },
    { book: 'mateo', bookName: 'Mateo', chapter: 6, verse: 21, label: 'Mateo 6:21' },
    { book: 'mateo', bookName: 'Mateo', chapter: 6, verse: 33, label: 'Mateo 6:33' },
    { book: 'mateo', bookName: 'Mateo', chapter: 7, verse: 7, label: 'Mateo 7:7' },
    { book: 'mateo', bookName: 'Mateo', chapter: 7, verse: 8, label: 'Mateo 7:8' },
    { book: 'mateo', bookName: 'Mateo', chapter: 7, verse: 12, label: 'Mateo 7:12' },
    { book: 'mateo', bookName: 'Mateo', chapter: 9, verse: 13, label: 'Mateo 9:13' },
    { book: 'mateo', bookName: 'Mateo', chapter: 10, verse: 39, label: 'Mateo 10:39' },
    { book: 'mateo', bookName: 'Mateo', chapter: 11, verse: 28, label: 'Mateo 11:28' },
    { book: 'mateo', bookName: 'Mateo', chapter: 11, verse: 29, label: 'Mateo 11:29' },
    { book: 'mateo', bookName: 'Mateo', chapter: 11, verse: 30, label: 'Mateo 11:30' },
    { book: 'mateo', bookName: 'Mateo', chapter: 14, verse: 27, label: 'Mateo 14:27' },
    { book: 'mateo', bookName: 'Mateo', chapter: 16, verse: 24, label: 'Mateo 16:24' },
    { book: 'mateo', bookName: 'Mateo', chapter: 18, verse: 20, label: 'Mateo 18:20' },
    { book: 'mateo', bookName: 'Mateo', chapter: 19, verse: 14, label: 'Mateo 19:14' },
    { book: 'mateo', bookName: 'Mateo', chapter: 19, verse: 26, label: 'Mateo 19:26' },
    { book: 'mateo', bookName: 'Mateo', chapter: 21, verse: 22, label: 'Mateo 21:22' },
    { book: 'mateo', bookName: 'Mateo', chapter: 22, verse: 37, label: 'Mateo 22:37' },
    { book: 'mateo', bookName: 'Mateo', chapter: 22, verse: 39, label: 'Mateo 22:39' },
    { book: 'mateo', bookName: 'Mateo', chapter: 24, verse: 35, label: 'Mateo 24:35' },
    { book: 'mateo', bookName: 'Mateo', chapter: 25, verse: 21, label: 'Mateo 25:21' },
    { book: 'mateo', bookName: 'Mateo', chapter: 26, verse: 41, label: 'Mateo 26:41' },
    { book: 'mateo', bookName: 'Mateo', chapter: 28, verse: 18, label: 'Mateo 28:18' },
    { book: 'mateo', bookName: 'Mateo', chapter: 28, verse: 19, label: 'Mateo 28:19' },
    { book: 'mateo', bookName: 'Mateo', chapter: 28, verse: 20, label: 'Mateo 28:20' },
    { book: 'marcos', bookName: 'Marcos', chapter: 1, verse: 17, label: 'Marcos 1:17' },
    { book: 'marcos', bookName: 'Marcos', chapter: 2, verse: 17, label: 'Marcos 2:17' },
    { book: 'marcos', bookName: 'Marcos', chapter: 4, verse: 39, label: 'Marcos 4:39' },
    { book: 'marcos', bookName: 'Marcos', chapter: 5, verse: 36, label: 'Marcos 5:36' },
    { book: 'marcos', bookName: 'Marcos', chapter: 8, verse: 36, label: 'Marcos 8:36' },
    { book: 'marcos', bookName: 'Marcos', chapter: 9, verse: 23, label: 'Marcos 9:23' },
    { book: 'marcos', bookName: 'Marcos', chapter: 10, verse: 27, label: 'Marcos 10:27' },
    { book: 'marcos', bookName: 'Marcos', chapter: 10, verse: 45, label: 'Marcos 10:45' },
    { book: 'marcos', bookName: 'Marcos', chapter: 11, verse: 24, label: 'Marcos 11:24' },
    { book: 'marcos', bookName: 'Marcos', chapter: 12, verse: 30, label: 'Marcos 12:30' },
    { book: 'marcos', bookName: 'Marcos', chapter: 13, verse: 31, label: 'Marcos 13:31' },
    { book: 'marcos', bookName: 'Marcos', chapter: 16, verse: 15, label: 'Marcos 16:15' },
    { book: 'lucas', bookName: 'Lucas', chapter: 1, verse: 37, label: 'Lucas 1:37' },
    { book: 'lucas', bookName: 'Lucas', chapter: 1, verse: 52, label: 'Lucas 1:52' },
    { book: 'lucas', bookName: 'Lucas', chapter: 2, verse: 11, label: 'Lucas 2:11' },
    { book: 'lucas', bookName: 'Lucas', chapter: 2, verse: 19, label: 'Lucas 2:19' },
    { book: 'lucas', bookName: 'Lucas', chapter: 4, verse: 18, label: 'Lucas 4:18' },
    { book: 'lucas', bookName: 'Lucas', chapter: 5, verse: 32, label: 'Lucas 5:32' },
    { book: 'lucas', bookName: 'Lucas', chapter: 6, verse: 31, label: 'Lucas 6:31' },
    { book: 'lucas', bookName: 'Lucas', chapter: 6, verse: 38, label: 'Lucas 6:38' },
    { book: 'lucas', bookName: 'Lucas', chapter: 9, verse: 23, label: 'Lucas 9:23' },
    { book: 'lucas', bookName: 'Lucas', chapter: 10, verse: 27, label: 'Lucas 10:27' },
    { book: 'lucas', bookName: 'Lucas', chapter: 11, verse: 9, label: 'Lucas 11:9' },
    { book: 'lucas', bookName: 'Lucas', chapter: 12, verse: 32, label: 'Lucas 12:32' },
    { book: 'lucas', bookName: 'Lucas', chapter: 15, verse: 7, label: 'Lucas 15:7' },
    { book: 'lucas', bookName: 'Lucas', chapter: 15, verse: 10, label: 'Lucas 15:10' },
    { book: 'lucas', bookName: 'Lucas', chapter: 18, verse: 1, label: 'Lucas 18:1' },
    { book: 'lucas', bookName: 'Lucas', chapter: 19, verse: 10, label: 'Lucas 19:10' },
    { book: 'lucas', bookName: 'Lucas', chapter: 21, verse: 33, label: 'Lucas 21:33' },
    { book: 'lucas', bookName: 'Lucas', chapter: 22, verse: 42, label: 'Lucas 22:42' },
    { book: 'lucas', bookName: 'Lucas', chapter: 24, verse: 6, label: 'Lucas 24:6' },
    { book: 'juan', bookName: 'Juan', chapter: 1, verse: 1, label: 'Juan 1:1' },
    { book: 'juan', bookName: 'Juan', chapter: 1, verse: 12, label: 'Juan 1:12' },
    { book: 'juan', bookName: 'Juan', chapter: 1, verse: 14, label: 'Juan 1:14' },
    { book: 'juan', bookName: 'Juan', chapter: 3, verse: 3, label: 'Juan 3:3' },
    { book: 'juan', bookName: 'Juan', chapter: 3, verse: 5, label: 'Juan 3:5' },
    { book: 'juan', bookName: 'Juan', chapter: 3, verse: 16, label: 'Juan 3:16' },
    { book: 'juan', bookName: 'Juan', chapter: 3, verse: 17, label: 'Juan 3:17' },
    { book: 'juan', bookName: 'Juan', chapter: 3, verse: 36, label: 'Juan 3:36' },
    { book: 'juan', bookName: 'Juan', chapter: 4, verse: 14, label: 'Juan 4:14' },
    { book: 'juan', bookName: 'Juan', chapter: 4, verse: 24, label: 'Juan 4:24' },
    { book: 'juan', bookName: 'Juan', chapter: 5, verse: 24, label: 'Juan 5:24' },
    { book: 'juan', bookName: 'Juan', chapter: 6, verse: 35, label: 'Juan 6:35' },
    { book: 'juan', bookName: 'Juan', chapter: 6, verse: 37, label: 'Juan 6:37' },
    { book: 'juan', bookName: 'Juan', chapter: 7, verse: 38, label: 'Juan 7:38' },
    { book: 'juan', bookName: 'Juan', chapter: 8, verse: 12, label: 'Juan 8:12' },
    { book: 'juan', bookName: 'Juan', chapter: 8, verse: 32, label: 'Juan 8:32' },
    { book: 'juan', bookName: 'Juan', chapter: 8, verse: 36, label: 'Juan 8:36' },
    { book: 'juan', bookName: 'Juan', chapter: 10, verse: 10, label: 'Juan 10:10' },
    { book: 'juan', bookName: 'Juan', chapter: 10, verse: 11, label: 'Juan 10:11' },
    { book: 'juan', bookName: 'Juan', chapter: 10, verse: 28, label: 'Juan 10:28' },
    { book: 'juan', bookName: 'Juan', chapter: 11, verse: 25, label: 'Juan 11:25' },
    { book: 'juan', bookName: 'Juan', chapter: 12, verse: 46, label: 'Juan 12:46' },
    { book: 'juan', bookName: 'Juan', chapter: 13, verse: 34, label: 'Juan 13:34' },
    { book: 'juan', bookName: 'Juan', chapter: 13, verse: 35, label: 'Juan 13:35' },
    { book: 'juan', bookName: 'Juan', chapter: 14, verse: 1, label: 'Juan 14:1' },
    { book: 'juan', bookName: 'Juan', chapter: 14, verse: 2, label: 'Juan 14:2' },
    { book: 'juan', bookName: 'Juan', chapter: 14, verse: 6, label: 'Juan 14:6' },
    { book: 'juan', bookName: 'Juan', chapter: 14, verse: 16, label: 'Juan 14:16' },
    { book: 'juan', bookName: 'Juan', chapter: 14, verse: 27, label: 'Juan 14:27' },
    { book: 'juan', bookName: 'Juan', chapter: 15, verse: 4, label: 'Juan 15:4' },
    { book: 'juan', bookName: 'Juan', chapter: 15, verse: 5, label: 'Juan 15:5' },
    { book: 'juan', bookName: 'Juan', chapter: 15, verse: 12, label: 'Juan 15:12' },
    { book: 'juan', bookName: 'Juan', chapter: 15, verse: 13, label: 'Juan 15:13' },
    { book: 'juan', bookName: 'Juan', chapter: 16, verse: 33, label: 'Juan 16:33' },
    { book: 'juan', bookName: 'Juan', chapter: 17, verse: 3, label: 'Juan 17:3' },
    { book: 'juan', bookName: 'Juan', chapter: 17, verse: 17, label: 'Juan 17:17' },
    { book: 'juan', bookName: 'Juan', chapter: 19, verse: 30, label: 'Juan 19:30' },
    { book: 'juan', bookName: 'Juan', chapter: 20, verse: 29, label: 'Juan 20:29' },
    { book: 'juan', bookName: 'Juan', chapter: 21, verse: 22, label: 'Juan 21:22' },
    { book: 'hechos', bookName: 'Hechos', chapter: 1, verse: 8, label: 'Hechos 1:8' },
    { book: 'hechos', bookName: 'Hechos', chapter: 2, verse: 21, label: 'Hechos 2:21' },
    { book: 'hechos', bookName: 'Hechos', chapter: 2, verse: 38, label: 'Hechos 2:38' },
    { book: 'hechos', bookName: 'Hechos', chapter: 2, verse: 42, label: 'Hechos 2:42' },
    { book: 'hechos', bookName: 'Hechos', chapter: 3, verse: 6, label: 'Hechos 3:6' },
    { book: 'hechos', bookName: 'Hechos', chapter: 4, verse: 12, label: 'Hechos 4:12' },
    { book: 'hechos', bookName: 'Hechos', chapter: 5, verse: 29, label: 'Hechos 5:29' },
    { book: 'hechos', bookName: 'Hechos', chapter: 9, verse: 15, label: 'Hechos 9:15' },
    { book: 'hechos', bookName: 'Hechos', chapter: 10, verse: 34, label: 'Hechos 10:34' },
    { book: 'hechos', bookName: 'Hechos', chapter: 13, verse: 47, label: 'Hechos 13:47' },
    { book: 'hechos', bookName: 'Hechos', chapter: 16, verse: 31, label: 'Hechos 16:31' },
    { book: 'hechos', bookName: 'Hechos', chapter: 17, verse: 28, label: 'Hechos 17:28' },
    { book: 'hechos', bookName: 'Hechos', chapter: 18, verse: 10, label: 'Hechos 18:10' },
    { book: 'hechos', bookName: 'Hechos', chapter: 20, verse: 24, label: 'Hechos 20:24' },
    { book: 'hechos', bookName: 'Hechos', chapter: 20, verse: 35, label: 'Hechos 20:35' },
    { book: 'hechos', bookName: 'Hechos', chapter: 27, verse: 24, label: 'Hechos 27:24' },
    { book: 'romanos', bookName: 'Romanos', chapter: 1, verse: 16, label: 'Romanos 1:16' },
    { book: 'romanos', bookName: 'Romanos', chapter: 1, verse: 17, label: 'Romanos 1:17' },
    { book: 'romanos', bookName: 'Romanos', chapter: 3, verse: 23, label: 'Romanos 3:23' },
    { book: 'romanos', bookName: 'Romanos', chapter: 3, verse: 24, label: 'Romanos 3:24' },
    { book: 'romanos', bookName: 'Romanos', chapter: 4, verse: 20, label: 'Romanos 4:20' },
    { book: 'romanos', bookName: 'Romanos', chapter: 5, verse: 1, label: 'Romanos 5:1' },
    { book: 'romanos', bookName: 'Romanos', chapter: 5, verse: 3, label: 'Romanos 5:3' },
    { book: 'romanos', bookName: 'Romanos', chapter: 5, verse: 5, label: 'Romanos 5:5' },
    { book: 'romanos', bookName: 'Romanos', chapter: 5, verse: 8, label: 'Romanos 5:8' },
    { book: 'romanos', bookName: 'Romanos', chapter: 6, verse: 23, label: 'Romanos 6:23' },
    { book: 'romanos', bookName: 'Romanos', chapter: 8, verse: 1, label: 'Romanos 8:1' },
    { book: 'romanos', bookName: 'Romanos', chapter: 8, verse: 18, label: 'Romanos 8:18' },
    { book: 'romanos', bookName: 'Romanos', chapter: 8, verse: 26, label: 'Romanos 8:26' },
    { book: 'romanos', bookName: 'Romanos', chapter: 8, verse: 28, label: 'Romanos 8:28' },
    { book: 'romanos', bookName: 'Romanos', chapter: 8, verse: 31, label: 'Romanos 8:31' },
    { book: 'romanos', bookName: 'Romanos', chapter: 8, verse: 32, label: 'Romanos 8:32' },
    { book: 'romanos', bookName: 'Romanos', chapter: 8, verse: 37, label: 'Romanos 8:37' },
    { book: 'romanos', bookName: 'Romanos', chapter: 8, verse: 38, label: 'Romanos 8:38' },
    { book: 'romanos', bookName: 'Romanos', chapter: 10, verse: 9, label: 'Romanos 10:9' },
    { book: 'romanos', bookName: 'Romanos', chapter: 10, verse: 10, label: 'Romanos 10:10' },
    { book: 'romanos', bookName: 'Romanos', chapter: 10, verse: 13, label: 'Romanos 10:13' },
    { book: 'romanos', bookName: 'Romanos', chapter: 10, verse: 17, label: 'Romanos 10:17' },
    { book: 'romanos', bookName: 'Romanos', chapter: 11, verse: 33, label: 'Romanos 11:33' },
    { book: 'romanos', bookName: 'Romanos', chapter: 12, verse: 1, label: 'Romanos 12:1' },
    { book: 'romanos', bookName: 'Romanos', chapter: 12, verse: 2, label: 'Romanos 12:2' },
    { book: 'romanos', bookName: 'Romanos', chapter: 12, verse: 12, label: 'Romanos 12:12' },
    { book: 'romanos', bookName: 'Romanos', chapter: 12, verse: 21, label: 'Romanos 12:21' },
    { book: 'romanos', bookName: 'Romanos', chapter: 13, verse: 1, label: 'Romanos 13:1' },
    { book: 'romanos', bookName: 'Romanos', chapter: 14, verse: 17, label: 'Romanos 14:17' },
    { book: 'romanos', bookName: 'Romanos', chapter: 15, verse: 13, label: 'Romanos 15:13' },
    { book: 'romanos', bookName: 'Romanos', chapter: 16, verse: 20, label: 'Romanos 16:20' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 1, verse: 18, label: '1 Corintios 1:18' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 2, verse: 9, label: '1 Corintios 2:9' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 3, verse: 16, label: '1 Corintios 3:16' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 4, verse: 20, label: '1 Corintios 4:20' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 6, verse: 19, label: '1 Corintios 6:19' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 6, verse: 20, label: '1 Corintios 6:20' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 9, verse: 24, label: '1 Corintios 9:24' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 10, verse: 13, label: '1 Corintios 10:13' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 10, verse: 31, label: '1 Corintios 10:31' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 12, verse: 27, label: '1 Corintios 12:27' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 13, verse: 1, label: '1 Corintios 13:1' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 13, verse: 2, label: '1 Corintios 13:2' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 13, verse: 4, label: '1 Corintios 13:4' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 13, verse: 8, label: '1 Corintios 13:8' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 13, verse: 13, label: '1 Corintios 13:13' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 14, verse: 40, label: '1 Corintios 14:40' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 15, verse: 33, label: '1 Corintios 15:33' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 15, verse: 57, label: '1 Corintios 15:57' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 15, verse: 58, label: '1 Corintios 15:58' },
    { book: '1corintios', bookName: '1 Corintios', chapter: 16, verse: 14, label: '1 Corintios 16:14' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 1, verse: 3, label: '2 Corintios 1:3' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 1, verse: 20, label: '2 Corintios 1:20' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 3, verse: 17, label: '2 Corintios 3:17' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 4, verse: 7, label: '2 Corintios 4:7' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 4, verse: 16, label: '2 Corintios 4:16' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 4, verse: 17, label: '2 Corintios 4:17' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 5, verse: 7, label: '2 Corintios 5:7' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 5, verse: 17, label: '2 Corintios 5:17' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 5, verse: 21, label: '2 Corintios 5:21' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 6, verse: 2, label: '2 Corintios 6:2' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 9, verse: 7, label: '2 Corintios 9:7' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 9, verse: 8, label: '2 Corintios 9:8' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 10, verse: 4, label: '2 Corintios 10:4' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 12, verse: 9, label: '2 Corintios 12:9' },
    { book: '2corintios', bookName: '2 Corintios', chapter: 13, verse: 14, label: '2 Corintios 13:14' },
    { book: 'galatas', bookName: 'Gálatas', chapter: 2, verse: 20, label: 'Gálatas 2:20' },
    { book: 'galatas', bookName: 'Gálatas', chapter: 3, verse: 28, label: 'Gálatas 3:28' },
    { book: 'galatas', bookName: 'Gálatas', chapter: 5, verse: 1, label: 'Gálatas 5:1' },
    { book: 'galatas', bookName: 'Gálatas', chapter: 5, verse: 13, label: 'Gálatas 5:13' },
    { book: 'galatas', bookName: 'Gálatas', chapter: 5, verse: 16, label: 'Gálatas 5:16' },
    { book: 'galatas', bookName: 'Gálatas', chapter: 5, verse: 22, label: 'Gálatas 5:22' },
    { book: 'galatas', bookName: 'Gálatas', chapter: 6, verse: 7, label: 'Gálatas 6:7' },
    { book: 'galatas', bookName: 'Gálatas', chapter: 6, verse: 9, label: 'Gálatas 6:9' },
    { book: 'efesios', bookName: 'Efesios', chapter: 1, verse: 3, label: 'Efesios 1:3' },
    { book: 'efesios', bookName: 'Efesios', chapter: 1, verse: 7, label: 'Efesios 1:7' },
    { book: 'efesios', bookName: 'Efesios', chapter: 1, verse: 11, label: 'Efesios 1:11' },
    { book: 'efesios', bookName: 'Efesios', chapter: 2, verse: 4, label: 'Efesios 2:4' },
    { book: 'efesios', bookName: 'Efesios', chapter: 2, verse: 8, label: 'Efesios 2:8' },
    { book: 'efesios', bookName: 'Efesios', chapter: 2, verse: 10, label: 'Efesios 2:10' },
    { book: 'efesios', bookName: 'Efesios', chapter: 3, verse: 16, label: 'Efesios 3:16' },
    { book: 'efesios', bookName: 'Efesios', chapter: 3, verse: 20, label: 'Efesios 3:20' },
    { book: 'efesios', bookName: 'Efesios', chapter: 4, verse: 32, label: 'Efesios 4:32' },
    { book: 'efesios', bookName: 'Efesios', chapter: 5, verse: 1, label: 'Efesios 5:1' },
    { book: 'efesios', bookName: 'Efesios', chapter: 5, verse: 18, label: 'Efesios 5:18' },
    { book: 'efesios', bookName: 'Efesios', chapter: 6, verse: 10, label: 'Efesios 6:10' },
    { book: 'efesios', bookName: 'Efesios', chapter: 6, verse: 11, label: 'Efesios 6:11' },
    { book: 'efesios', bookName: 'Efesios', chapter: 6, verse: 12, label: 'Efesios 6:12' },
    { book: 'efesios', bookName: 'Efesios', chapter: 6, verse: 13, label: 'Efesios 6:13' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 1, verse: 6, label: 'Filipenses 1:6' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 1, verse: 21, label: 'Filipenses 1:21' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 2, verse: 3, label: 'Filipenses 2:3' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 2, verse: 5, label: 'Filipenses 2:5' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 2, verse: 11, label: 'Filipenses 2:11' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 2, verse: 14, label: 'Filipenses 2:14' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 3, verse: 8, label: 'Filipenses 3:8' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 3, verse: 13, label: 'Filipenses 3:13' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 3, verse: 14, label: 'Filipenses 3:14' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 4, verse: 4, label: 'Filipenses 4:4' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 4, verse: 6, label: 'Filipenses 4:6' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 4, verse: 7, label: 'Filipenses 4:7' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 4, verse: 8, label: 'Filipenses 4:8' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 4, verse: 13, label: 'Filipenses 4:13' },
    { book: 'filipenses', bookName: 'Filipenses', chapter: 4, verse: 19, label: 'Filipenses 4:19' },
    { book: 'colosenses', bookName: 'Colosenses', chapter: 1, verse: 13, label: 'Colosenses 1:13' },
    { book: 'colosenses', bookName: 'Colosenses', chapter: 1, verse: 16, label: 'Colosenses 1:16' },
    { book: 'colosenses', bookName: 'Colosenses', chapter: 1, verse: 17, label: 'Colosenses 1:17' },
    { book: 'colosenses', bookName: 'Colosenses', chapter: 2, verse: 6, label: 'Colosenses 2:6' },
    { book: 'colosenses', bookName: 'Colosenses', chapter: 3, verse: 1, label: 'Colosenses 3:1' },
    { book: 'colosenses', bookName: 'Colosenses', chapter: 3, verse: 2, label: 'Colosenses 3:2' },
    { book: 'colosenses', bookName: 'Colosenses', chapter: 3, verse: 12, label: 'Colosenses 3:12' },
    { book: 'colosenses', bookName: 'Colosenses', chapter: 3, verse: 14, label: 'Colosenses 3:14' },
    { book: 'colosenses', bookName: 'Colosenses', chapter: 3, verse: 16, label: 'Colosenses 3:16' },
    { book: 'colosenses', bookName: 'Colosenses', chapter: 3, verse: 23, label: 'Colosenses 3:23' },
    { book: 'colosenses', bookName: 'Colosenses', chapter: 4, verse: 2, label: 'Colosenses 4:2' },
    { book: '1tesalonicenses', bookName: '1 Tesalonicenses', chapter: 1, verse: 5, label: '1 Tesalonicenses 1:5' },
    { book: '1tesalonicenses', bookName: '1 Tesalonicenses', chapter: 2, verse: 13, label: '1 Tesalonicenses 2:13' },
    { book: '1tesalonicenses', bookName: '1 Tesalonicenses', chapter: 4, verse: 16, label: '1 Tesalonicenses 4:16' },
    { book: '1tesalonicenses', bookName: '1 Tesalonicenses', chapter: 5, verse: 11, label: '1 Tesalonicenses 5:11' },
    { book: '1tesalonicenses', bookName: '1 Tesalonicenses', chapter: 5, verse: 16, label: '1 Tesalonicenses 5:16' },
    { book: '1tesalonicenses', bookName: '1 Tesalonicenses', chapter: 5, verse: 17, label: '1 Tesalonicenses 5:17' },
    { book: '1tesalonicenses', bookName: '1 Tesalonicenses', chapter: 5, verse: 18, label: '1 Tesalonicenses 5:18' },
    { book: '1tesalonicenses', bookName: '1 Tesalonicenses', chapter: 5, verse: 23, label: '1 Tesalonicenses 5:23' },
    { book: '2tesalonicenses', bookName: '2 Tesalonicenses', chapter: 1, verse: 7, label: '2 Tesalonicenses 1:7' },
    { book: '2tesalonicenses', bookName: '2 Tesalonicenses', chapter: 2, verse: 16, label: '2 Tesalonicenses 2:16' },
    { book: '2tesalonicenses', bookName: '2 Tesalonicenses', chapter: 3, verse: 3, label: '2 Tesalonicenses 3:3' },
    { book: '2tesalonicenses', bookName: '2 Tesalonicenses', chapter: 3, verse: 5, label: '2 Tesalonicenses 3:5' },
    { book: '1timoteo', bookName: '1 Timoteo', chapter: 1, verse: 15, label: '1 Timoteo 1:15' },
    { book: '1timoteo', bookName: '1 Timoteo', chapter: 2, verse: 5, label: '1 Timoteo 2:5' },
    { book: '1timoteo', bookName: '1 Timoteo', chapter: 4, verse: 8, label: '1 Timoteo 4:8' },
    { book: '1timoteo', bookName: '1 Timoteo', chapter: 4, verse: 12, label: '1 Timoteo 4:12' },
    { book: '1timoteo', bookName: '1 Timoteo', chapter: 6, verse: 6, label: '1 Timoteo 6:6' },
    { book: '1timoteo', bookName: '1 Timoteo', chapter: 6, verse: 10, label: '1 Timoteo 6:10' },
    { book: '1timoteo', bookName: '1 Timoteo', chapter: 6, verse: 12, label: '1 Timoteo 6:12' },
    { book: '2timoteo', bookName: '2 Timoteo', chapter: 1, verse: 7, label: '2 Timoteo 1:7' },
    { book: '2timoteo', bookName: '2 Timoteo', chapter: 1, verse: 12, label: '2 Timoteo 1:12' },
    { book: '2timoteo', bookName: '2 Timoteo', chapter: 2, verse: 3, label: '2 Timoteo 2:3' },
    { book: '2timoteo', bookName: '2 Timoteo', chapter: 2, verse: 15, label: '2 Timoteo 2:15' },
    { book: '2timoteo', bookName: '2 Timoteo', chapter: 3, verse: 16, label: '2 Timoteo 3:16' },
    { book: '2timoteo', bookName: '2 Timoteo', chapter: 4, verse: 7, label: '2 Timoteo 4:7' },
    { book: '2timoteo', bookName: '2 Timoteo', chapter: 4, verse: 8, label: '2 Timoteo 4:8' },
    { book: '2timoteo', bookName: '2 Timoteo', chapter: 4, verse: 18, label: '2 Timoteo 4:18' },
    { book: 'tito', bookName: 'Tito', chapter: 1, verse: 15, label: 'Tito 1:15' },
    { book: 'tito', bookName: 'Tito', chapter: 2, verse: 11, label: 'Tito 2:11' },
    { book: 'tito', bookName: 'Tito', chapter: 2, verse: 14, label: 'Tito 2:14' },
    { book: 'tito', bookName: 'Tito', chapter: 3, verse: 5, label: 'Tito 3:5' },
    { book: 'filemon', bookName: 'Filemón', chapter: 1, verse: 6, label: 'Filemón 1:6' },
    { book: 'filemon', bookName: 'Filemón', chapter: 1, verse: 7, label: 'Filemón 1:7' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 1, verse: 3, label: 'Hebreos 1:3' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 2, verse: 18, label: 'Hebreos 2:18' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 4, verse: 12, label: 'Hebreos 4:12' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 4, verse: 15, label: 'Hebreos 4:15' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 4, verse: 16, label: 'Hebreos 4:16' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 6, verse: 10, label: 'Hebreos 6:10' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 10, verse: 23, label: 'Hebreos 10:23' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 10, verse: 25, label: 'Hebreos 10:25' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 11, verse: 1, label: 'Hebreos 11:1' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 11, verse: 6, label: 'Hebreos 11:6' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 12, verse: 1, label: 'Hebreos 12:1' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 12, verse: 2, label: 'Hebreos 12:2' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 12, verse: 11, label: 'Hebreos 12:11' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 13, verse: 5, label: 'Hebreos 13:5' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 13, verse: 6, label: 'Hebreos 13:6' },
    { book: 'hebreos', bookName: 'Hebreos', chapter: 13, verse: 8, label: 'Hebreos 13:8' },
    { book: 'santiago', bookName: 'Santiago', chapter: 1, verse: 2, label: 'Santiago 1:2' },
    { book: 'santiago', bookName: 'Santiago', chapter: 1, verse: 5, label: 'Santiago 1:5' },
    { book: 'santiago', bookName: 'Santiago', chapter: 1, verse: 12, label: 'Santiago 1:12' },
    { book: 'santiago', bookName: 'Santiago', chapter: 1, verse: 17, label: 'Santiago 1:17' },
    { book: 'santiago', bookName: 'Santiago', chapter: 2, verse: 26, label: 'Santiago 2:26' },
    { book: 'santiago', bookName: 'Santiago', chapter: 3, verse: 17, label: 'Santiago 3:17' },
    { book: 'santiago', bookName: 'Santiago', chapter: 4, verse: 7, label: 'Santiago 4:7' },
    { book: 'santiago', bookName: 'Santiago', chapter: 4, verse: 8, label: 'Santiago 4:8' },
    { book: 'santiago', bookName: 'Santiago', chapter: 4, verse: 10, label: 'Santiago 4:10' },
    { book: 'santiago', bookName: 'Santiago', chapter: 5, verse: 16, label: 'Santiago 5:16' },
    { book: '1pedro', bookName: '1 Pedro', chapter: 1, verse: 3, label: '1 Pedro 1:3' },
    { book: '1pedro', bookName: '1 Pedro', chapter: 1, verse: 7, label: '1 Pedro 1:7' },
    { book: '1pedro', bookName: '1 Pedro', chapter: 1, verse: 15, label: '1 Pedro 1:15' },
    { book: '1pedro', bookName: '1 Pedro', chapter: 2, verse: 2, label: '1 Pedro 2:2' },
    { book: '1pedro', bookName: '1 Pedro', chapter: 2, verse: 9, label: '1 Pedro 2:9' },
    { book: '1pedro', bookName: '1 Pedro', chapter: 3, verse: 15, label: '1 Pedro 3:15' },
    { book: '1pedro', bookName: '1 Pedro', chapter: 4, verse: 8, label: '1 Pedro 4:8' },
    { book: '1pedro', bookName: '1 Pedro', chapter: 5, verse: 6, label: '1 Pedro 5:6' },
    { book: '1pedro', bookName: '1 Pedro', chapter: 5, verse: 7, label: '1 Pedro 5:7' },
    { book: '1pedro', bookName: '1 Pedro', chapter: 5, verse: 10, label: '1 Pedro 5:10' },
    { book: '2pedro', bookName: '2 Pedro', chapter: 1, verse: 3, label: '2 Pedro 1:3' },
    { book: '2pedro', bookName: '2 Pedro', chapter: 1, verse: 4, label: '2 Pedro 1:4' },
    { book: '2pedro', bookName: '2 Pedro', chapter: 1, verse: 21, label: '2 Pedro 1:21' },
    { book: '2pedro', bookName: '2 Pedro', chapter: 3, verse: 9, label: '2 Pedro 3:9' },
    { book: '2pedro', bookName: '2 Pedro', chapter: 3, verse: 18, label: '2 Pedro 3:18' },
    { book: '1juan', bookName: '1 Juan', chapter: 1, verse: 5, label: '1 Juan 1:5' },
    { book: '1juan', bookName: '1 Juan', chapter: 1, verse: 7, label: '1 Juan 1:7' },
    { book: '1juan', bookName: '1 Juan', chapter: 1, verse: 9, label: '1 Juan 1:9' },
    { book: '1juan', bookName: '1 Juan', chapter: 2, verse: 17, label: '1 Juan 2:17' },
    { book: '1juan', bookName: '1 Juan', chapter: 3, verse: 1, label: '1 Juan 3:1' },
    { book: '1juan', bookName: '1 Juan', chapter: 3, verse: 16, label: '1 Juan 3:16' },
    { book: '1juan', bookName: '1 Juan', chapter: 3, verse: 18, label: '1 Juan 3:18' },
    { book: '1juan', bookName: '1 Juan', chapter: 4, verse: 4, label: '1 Juan 4:4' },
    { book: '1juan', bookName: '1 Juan', chapter: 4, verse: 7, label: '1 Juan 4:7' },
    { book: '1juan', bookName: '1 Juan', chapter: 4, verse: 8, label: '1 Juan 4:8' },
    { book: '1juan', bookName: '1 Juan', chapter: 4, verse: 16, label: '1 Juan 4:16' },
    { book: '1juan', bookName: '1 Juan', chapter: 4, verse: 18, label: '1 Juan 4:18' },
    { book: '1juan', bookName: '1 Juan', chapter: 4, verse: 19, label: '1 Juan 4:19' },
    { book: '1juan', bookName: '1 Juan', chapter: 5, verse: 4, label: '1 Juan 5:4' },
    { book: '1juan', bookName: '1 Juan', chapter: 5, verse: 14, label: '1 Juan 5:14' },
    { book: '2juan', bookName: '2 Juan', chapter: 1, verse: 3, label: '2 Juan 1:3' },
    { book: '2juan', bookName: '2 Juan', chapter: 1, verse: 6, label: '2 Juan 1:6' },
    { book: '3juan', bookName: '3 Juan', chapter: 1, verse: 2, label: '3 Juan 1:2' },
    { book: '3juan', bookName: '3 Juan', chapter: 1, verse: 11, label: '3 Juan 1:11' },
    { book: 'judas', bookName: 'Judas', chapter: 1, verse: 2, label: 'Judas 1:2' },
    { book: 'judas', bookName: 'Judas', chapter: 1, verse: 24, label: 'Judas 1:24' },
    { book: 'judas', bookName: 'Judas', chapter: 1, verse: 25, label: 'Judas 1:25' },
    { book: 'apocalipsis', bookName: 'Apocalipsis', chapter: 1, verse: 3, label: 'Apocalipsis 1:3' },
    { book: 'apocalipsis', bookName: 'Apocalipsis', chapter: 1, verse: 8, label: 'Apocalipsis 1:8' },
    { book: 'apocalipsis', bookName: 'Apocalipsis', chapter: 2, verse: 10, label: 'Apocalipsis 2:10' },
    { book: 'apocalipsis', bookName: 'Apocalipsis', chapter: 3, verse: 20, label: 'Apocalipsis 3:20' },
    { book: 'apocalipsis', bookName: 'Apocalipsis', chapter: 4, verse: 11, label: 'Apocalipsis 4:11' },
    { book: 'apocalipsis', bookName: 'Apocalipsis', chapter: 5, verse: 12, label: 'Apocalipsis 5:12' },
    { book: 'apocalipsis', bookName: 'Apocalipsis', chapter: 7, verse: 12, label: 'Apocalipsis 7:12' },
    { book: 'apocalipsis', bookName: 'Apocalipsis', chapter: 12, verse: 11, label: 'Apocalipsis 12:11' },
    { book: 'apocalipsis', bookName: 'Apocalipsis', chapter: 19, verse: 6, label: 'Apocalipsis 19:6' },
    { book: 'apocalipsis', bookName: 'Apocalipsis', chapter: 21, verse: 4, label: 'Apocalipsis 21:4' },
    { book: 'apocalipsis', bookName: 'Apocalipsis', chapter: 21, verse: 5, label: 'Apocalipsis 21:5' },
    { book: 'apocalipsis', bookName: 'Apocalipsis', chapter: 22, verse: 13, label: 'Apocalipsis 22:13' },
    { book: 'apocalipsis', bookName: 'Apocalipsis', chapter: 22, verse: 20, label: 'Apocalipsis 22:20' },
];

function dayOfYear(d: Date): number {
    const start = new Date(d.getFullYear(), 0, 0);
    return Math.floor((d.getTime() - start.getTime()) / 86400000);
}

export function pickVerseOfDay(date: Date = new Date()): VerseRef {
    const dayIndex = dayOfYear(date) - 1;
    const yearOffset = date.getFullYear() * 366;
    return VERSE_ROTATION[(yearOffset + dayIndex) % VERSE_ROTATION.length];
}
